# 课程： Python分析工业大数据

## 第四章 Numpy  




### Create Numpy Data 创建Numpy数据

In [3]:
import numpy as np

In [5]:
# 方式1: 利用python list生成ndarrays
y = np.array([30, 45, 65, 23])
print('y is {}'.format(y))


y is [30 45 65 23]


In [9]:
array_data = np.array([[1,2,3], [4,5,6]])

In [10]:
# 用method: shape 来了解数据结构
array_data.shape

(2, 3)

In [ ]:
# ToDo: 尝试用不同的list，生成ndarray


In [12]:
#用numpy函数来生成特定的numpy数据
#  np.zeros(), 
#  np.ones(), 
#  np.full(shape, constant value)
#  np.eye(N), 创建N x N 的 单位矩阵(Identity matrix)
#  np.arange(start, stop, step), 创建 序列
#  np.linspace(start, stop, step = 50)创建序列， 对非整step

zero_data = np.zeros((4,5))
zero_data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# ToDo: 练习用np.full()生成数据


In [13]:
# 了解数据类型的函数： type()
type(array_data)

numpy.ndarray

In [14]:
# 了解元素的数据类型的method： .dtype
array_data.dtype

dtype('int64')

In [18]:
I_matrix = np.eye(3)
I_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
print('I_matrix = \n', I_matrix)

I_matrix = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# 修改元素级别的数据类型， 用astype(), 
array_data = np.array([[1,2,3], [4,5,6]])

array_data.dtype

dtype('int64')

In [24]:
array_data_1 = array_data.astype(np.int64)

In [25]:
array_data.dtype

dtype('int64')

In [27]:
# 直接定义元素的数据类型
array_data = np.array([[1,2,3], [4,5,6]], dtype = 'int32')
array_data.dtype

dtype('int32')

In [34]:
# 修改数据的shape， 用reshape()函数
array_data = np.reshape(array_data, (3,2))
array_data

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [37]:
# 把reshape作为一种method来用
reshape_data = np.arange(12).reshape(3,4)
reshape_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
# 创建0-50间，均匀间隔的整数序列，并以2维展现(rank = 2)
space_data = np.linspace(0,20,10, endpoint=False).reshape(2,5)
space_data

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.]])

In [57]:
# 用np.random模块生成ndarray随机数
# np.random.random(shape), 生成在[0.0, 1.0)的shape结构的均分布随机数
# np.random.rand(shape), 生成在[0, 1)的shape结构的均分布随机数
# np.random.normal(mean, std, size=shape)生成正太分布数据
# np.random.randn(), 生成正太分布
# np.random.randint(low[, high, size]) 生成随机整数
# np.random.choice(a[, size, replace, p])生成随机样本


In [40]:
np.random.random((2,2))

array([[0.76387673, 0.00133998],
       [0.70860201, 0.09151233]])

In [52]:
np.random.normal(2, 1, size = (3,3))

array([[ 0.90875294,  2.95803115,  2.44260465],
       [ 2.54634649,  1.84960537,  3.57278043],
       [ 2.6222665 ,  2.5571392 , -0.44731762]])

In [51]:
# 比较
np.random.random((2,2))
np.random.rand(2,2)

array([[0.38464943, 0.71162327],
       [0.92199025, 0.24833436]])

In [56]:
np.random.choice(3, 2)
np.random.choice(3, 2, replace=False)

array([2, 0])

### 访问ndarrays数据元素

In [58]:
y = np.array([30, 45, 65, 23])

y[0]

30

In [59]:
array_data = np.array([[1,2,3], [4,5,6]])

array_data[0][1]

2

### 删除ndarrays数据元素

In [61]:
# np.delete(ndarray, elements, axis)

y =np.delete(y, [0,3])
y

array([45, 65])

In [62]:
 np.delete(array_data, 0, axis = 0)


In [67]:
np.delete(array_data, [0,1], axis = 1)

array([[3],
       [6]])

### 添加ndarrays数据元素

In [68]:
# np.append(ndarray, elements, axis)

array_data = np.array([[1,2,3], [4,5,6]])

np.append(array_data, [7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
np.append(array_data, [[7], [8]], axis = 1)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

### 插入ndarrays数据元素

In [72]:
y = np.array([30, 45, 65, 23])

np.insert(y, 2, [0,0])

array([30, 45,  0,  0, 65, 23])

### 堆叠ndarrays数据元素

In [73]:
# np.vstack()
# np.hstock()

### ndarrays切片

In [74]:
z = np.arange(20).reshape(4,5)

z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
z[1:, 2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

### ndarrays排序

In [76]:
y = np.array([30, 45, 65, 23])

# np.sort()
# when sorting rank 2 ndarrays
np.sort(y)

array([23, 30, 45, 65])

### 算术/基本运算

In [83]:
# np.add(x, y), np.subtract(x, y), np.multiply(x, y), np.divide(x, y)
# np.sqrt(x)， np.power(x, n)

x = np.array([1, 2, 3, 4])
y = np.array([1, 0.5, 1, 0.5])

In [84]:
x+y, x-y, x*y, x/y

(array([2. , 2.5, 4. , 4.5]),
 array([0. , 1.5, 2. , 3.5]),
 array([1., 1., 3., 2.]),
 array([1., 4., 3., 8.]))

In [85]:
np.sqrt([1,2,3,4]), np.power([1,2,3,4], 2)

(array([1.        , 1.41421356, 1.73205081, 2.        ]),
 array([ 1,  4,  9, 16]))

### Broadcasting

In [91]:
#例子1
np.array([1,2,3]) + 3,  np.array([1,2,3]) * 3, np.array([1,2,3]) - 3, np.array([1,2,3]) / 3

(array([4, 5, 6]),
 array([3, 6, 9]),
 array([-2, -1,  0]),
 array([0.33333333, 0.66666667, 1.        ]))

In [100]:
# 例子2
x = np.array([1, 2])
y = np.array([[1,2], [3, 4]])

print('x+y = \n', x+y)
print()
print('x-y = \n', x-y)
print()
print('x*y = \n', x*y)
print()
print('x/y = \n', x/y)
print()

x+y = 
 [[2 4]
 [4 6]]

x-y = 
 [[ 0  0]
 [-2 -2]]

x*y = 
 [[1 4]
 [3 8]]

x/y = 
 [[1.         1.        ]
 [0.33333333 0.5       ]]



### ndarray基本统计

In [ ]:
# method: .mean(), .sum(), .std(), .max(), .min(), 
# 函数： np.median()
# 对rank 2 的ndarray数据， 行统计： axis = 0； 列统计： axis = 1

In [103]:
X = np.random.rand(4).reshape(2,2)

In [105]:
X.mean(), X.mean(axis = 0)

(0.5433626050660408, array([0.59568046, 0.49104475]))